### ISSUE TITLE
AxiosInterceptor not being used

### ISSUE THREAD

**Issue by ayuksekkaya** [andissanayake/UnifiedApp#14]
I am trying to understand how you are using the AxiosInterceptor and I see that you added it as a component in your app.js but you are not using the axios instance where you added the interceptor. So how does this work?

**Comment by andissanayake** [comment]
Hi Please check [main.tsx](https://github.com/andissanayake/UnifiedApp/blob/master/src/web/src/main.tsx). Check this [link ](https://medium.com/@disa2aka/token-authentication-integration-testing-asp-net-32bdab0f9967)for more details. Don't hesitate to contact me for any help 👍 .

**Comment by andissanayake** [comment]
Hi Please check [main.tsx](https://github.com/andissanayake/UnifiedApp/blob/master/src/web/src/main.tsx). Check this [link ](https://medium.com/@disa2aka/token-authentication-integration-testing-asp-net-32bdab0f9967)for more details. Don't hesitate to contact me for any help 👍 .
